exp:
  name: oasis2-1.1
  project: gan-optimizers
  notes: "oasis2 test"

training:
  trainer: avg_gan
  num_epochs: 500
  num_iters: 1000
  num_val_iters: 10
  batch_size: 64
  val_batch_size: 128
  device: cuda

prior:
  dist: normal
  latent_dim: 128

dist_prior:
  normal:
    latent_dim: ${prior.latent_dim}

data:
  name: cifar10
  loader: infinite
  root: ../data/
  num_workers: 2

dataset:
  cifar10:
    train:
      root: ${data.root}
      train: True
    test:
      root: ${data.root}
      train: False

loader:
  infinite:
    prior:
      batch_size: ${training.batch_size}
      num_workers: ${data.num_workers}
      shuffle: False
      device: ${training.device}
    train:
      batch_size: ${training.batch_size}
      num_workers: ${data.num_workers}
      shuffle: True
      device: ${training.device}
    test:
      batch_size: ${training.batch_size}
      num_workers: ${data.num_workers}
      shuffle: False
      device: ${training.device}

metrics:
  fid_cache: ../data/stats/cifar10.train.npz

log:
  log_every: 100
  disc_logging_off: True
  calculate_every: 10
  small_val_size: 500
  val_size: 50000

gen:
  model: resnet_v2
  optim: oasis2
  loss_funcs:
    - hinge
  loss_coefs:
    - 1
  num_steps: 1
  lr: 2e-4
  weight_decay: 0
  betas:
    - 0.2
    - 0.999
  lr_decay: 1

gennets:
  resnet_v2:
    z_dim: ${prior.latent_dim}

gen_optim:
  oasis2:
    lr: ${gen.lr}
    betas: ${gen.betas}
    eps: 1e-2
    update_each: 20

disc:
  model: resnet_v2
  optim: oasis2
  loss_funcs:
    - hinge
  loss_coefs:
    - 1
  num_steps: 5
  lr: 2e-4
  weight_decay: 0
  betas:
    - 0.2
    - 0.999
  lr_decay: 1

disc_optim:
  oasis2:
    lr: ${disc.lr}
    betas: ${disc.betas}
    eps: 1e-2
    update_each: 20