defaults:
  - hydra_setup
  - adapter_setup
  - _self_
  - dataset: imagenet_v2
  # - prompting: mnist

eval:
  checkpoint_path: /home/myurachinskiy/CLIP/summer-clip/outputs/2022-07-24/17-42-56/checkpoints/epoch_20/model.ckpt
  train_config_path: # if none, it is deducted from checkpoint_path
  image_features_path: /home/myurachinskiy/CLIP/summer-clip/outputs/2022-07-25/16-18-44/image_features.pt

data:
  num_workers: 2
  batch_size: 512
