defaults:
  - hydra_setup
  - adapter_setup
  - saved_paths
  - _self_
  - dataset: imagenet_val_no_image
  - prompting: imagenet

clip:
  model_name: RN50

eval:
  image_features_path: ${saved_paths.image_features.ImageNet_val-RN50}

data:
  num_workers: 2
  batch_size: 512
