defaults:
  - hydra_setup
  - adapter_setup
  - saved_paths
  - _self_
  - dataset: eurosat
  - prompting: tip_eurosat

clip:
  model_name: RN50

eval:
  image_features_path: ${saved_paths.image_features.EuroSAT-RN50}

data:
  num_workers: 2
  batch_size: 512
