defaults:
  - hydra_setup
  - adapter_setup
  - _self_
  - dataset@train_dataset: tip_dataset_train
  - dataset@test_dataset: tip_dataset_test
  - prompting: tip_dtd

dataset_name: dtd
save_train_outs: true

clip:
  model_name: RN50

data:
  batch_size: 512
  num_workers: 2
