defaults:
  - hydra_setup
  - adapter_setup
  - _self_

# ------ root_path/dataset_name ------
root_path: ${path.cache_dir}


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# load_cache: True
# load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [20, 10]
search_step: [200, 20]

init_beta: 1
init_alpha: 3


# ------ Basic Config ------
dataset: stanford_cars
shots: 16
backbone: 'RN50'

lr: 0.001
augment_epoch: 1
train_epoch: 20

exp:
  project: tip_adapter
  name: initial_tip
