defaults:
  - hydra_setup
  - adapter_setup
  - saved_paths: clip_paths
  - _self_
  - dataset: tip_eurosat_train_no_image

clip:
  model_name: RN50

data:
  image_features_path: ${saved_paths.image_features.EuroSAT_tip_train-RN50}

em_model:
  _target_: summer_clip.clip_em.fixed_em.FixedMeansGM
  covariance_type: full
  # reg_covar: 1e-4
  random_state: ${meta.random_state}
  verbose: 2

save_model:
  name: clip_em.joblib

exp:
  project: clip_em
  name: clip_em_v1
