defaults:
  - hydra_setup
  - adapter_setup
  - _self_
  - adapter: original_image
  - dataset: imagenet_train_no_image
  # - prompting: cifar100

clip:
  model_name: ViT-B/16

data:
  batch_size: 32
  num_workers: 2
  validation_size: 0
  checkpoints_dir: checkpoints
  image_features_path: /home/myurachinskiy/CLIP/summer-clip/outputs/2022-07-22/12-56-22/image_features.pt

training:
  epochs_num: 200
  adam_params:
    lr: 0.002
    betas: [0.9, 0.98]
    eps: 0.000001
    weight_decay: 0.2
