defaults:
  - hydra_setup
  - meta_setup
  - _self_
  - dataset: tip_eurosat_train_no_image
  - prompting: tip_eurosat
  - saved_paths: clip_paths

clip:
  model_name: RN50
  image_features_path: ${saved_paths.image_features.EuroSAT_tip_train-RN50}

tokenizer:
  path: transformers.CLIPTokenizer
  # path: transformers.GPT2Tokenizer
  name: openai/clip-vit-base-patch32  # should not differ from large
  # name: gpt2-large
  set_pad_as_eos: false
  tokenize_classes_kwargs: {}
    # add_prefix_space: true

model:
  use_clip_gpt: true
  meta_cfg_path: /home/myurachinskiy/CLIP/summer-clip/outputs/2023-02-02/22-43-01/checkpoints/epoch_4/step_222605/model_cfg.yaml
  state_dict_path: /home/myurachinskiy/CLIP/summer-clip/outputs/2023-02-02/22-43-01/checkpoints/epoch_4/step_222605/model.ckpt

# prompt_model:
#   _target_: summer_clip.clip_prompt.prompt_learner.FluentPromptModel
#   model_cfg:
#     cdist_kwargs: {}

prompt_model:
  _target_: summer_clip.clip_prompt.autoprompt_learner.AutoPromptModel
  model_cfg:
    num_cands: 16
    search_steps: 4

# init_prompter:
#   _target_: summer_clip.clip_prompt.prompt_learner.InitNumTokensPrompter
#   token: <|startoftext|>
#   length: 5

init_prompter:
  _target_: summer_clip.clip_prompt.prompt_learner.InitRandomPrompter
  length: 16

text_batcher:
  path: summer_clip.clip_prompt.prompt_learner.ImageTextBatcher
  kwargs: {}

data_loader:
  train:
    batch_size: 16
    shuffle: true
    pin_memory: true
    num_workers: 4

dataset_info:
  k_shots: 16

collator:
  _target_: summer_clip.clip_prompt.prompt_learner.LeftPromptCollator
  clip_seq_len: 77

loss:
  clip: 1.0
  fluency: 0.1

training:
  epochs_num: 100
  info_steps: 1
  save_steps: null
  classes_batch_size: 10
  max_top_prompts: 50
  gradient_accumulation_steps: 1
  new_top_prompts_each_epoch: false
  checkpoints_dir: checkpoints/

log:
  calculate_every: 1

exp:
  project: train_clip_prompt
  name: prompt_v1
