defaults:
  - hydra_setup
  - meta_setup
  - _self_
  - dataset: tip_eurosat_train_no_image
  - prompting: tip_eurosat
  - saved_paths: clip_paths

clip:
  model_name: RN50
  image_features_path: ${saved_paths.image_features.EuroSAT_tip_train-RN50}

tokenizer:
  path: transformers.CLIPTokenizer
  name: openai/clip-vit-base-patch32  # should not differ from large
  set_pad_as_eos: false
  tokenize_classes_kwargs: {}

optim:
  weight_decay: 0.0005
  kwargs:
    lr: 0.002

scheduler:
  name: cosine
  warmup_part: 0.01

data_loader:
  train:
    batch_size: 32
    shuffle: true
    pin_memory: true
    num_workers: 4

dataset_info:
  k_shots: 16

training:
  epochs_num: 100
  info_steps: 1
  gradient_accumulation_steps: 1
  new_top_prompts_each_epoch: false
  checkpoints_dir: checkpoints/

log:
  calculate_every: 1

exp:
  project: train_clip_coop
  name: coop_v1
