defaults:
  - hydra_setup
  - adapter_setup
  - _self_
  - prompting: mnist

eval:
  checkpoint_path: /home/myurachinskiy/CLIP/summer-clip/outputs/2022-07-02/22-41-39/checkpoints/epoch_2/model.ckpt
  train_config_path: # if none, it is deducted from checkpoint_path

dataset:
  dataset_name: MNIST-train
  num_workers: 2
  batch_size: 32
