defaults:
  - hydra_setup
  - adapter_setup
  - _self_
  - dataset: mnist_test
  - prompting: mnist

clip:
  model_name: ViT-B/16

eval:
  image_features_path: /home/myurachinskiy/CLIP/summer-clip/outputs/2022-07-25/14-57-54/image_features.pt

data:
  num_workers: 2
  batch_size: 512
