defaults:
  - hydra_setup
  - adapter_setup
  - _self_
  - dataset: cifar10_train
  # - prompting: mnist

eval:
  checkpoint_path: /home/myurachinskiy/CLIP/summer-clip/outputs/2022-07-22/14-22-56/checkpoints/epoch_19/model.ckpt
  train_config_path: # if none, it is deducted from checkpoint_path
  image_features_path: /home/myurachinskiy/CLIP/summer-clip/outputs/2022-07-22/12-44-05/image_features.pt

data:
  num_workers: 2
  batch_size: 512
