defaults:
  - hydra_setup
  - adapter_setup
  - _self_
  - adapter: linear
  - prompting: mnist

clip:
  model_name: ViT-B/16

dataset:
  dataset_name: MNIST
  batch_size: 32
  num_workers: 2
  validation_size: 0.25

data:
  checkpoints_dir: checkpoints

training:
  learning_rate: 0.00001
  epochs_num: 20
